server:
  port: 6001

netty:
  port: 6002
  host: 0.0.0.0

spring:
  output:
    type: none
  kafka:
    bootstrap-servers: localhost:9092
    topic-out: test
  mqtt:
    host: 127.0.0.1
    port: 1883
    client-id: agent_client
    topic-out: test

company:
  id: COM0000000I

wave:
  oneday-get-wave-count: 1

logging:
  file:
    name: ./logs/logger.log
  level:
    root: info
